fix

diff --git a/.github/workflows/dependency-analysis.yml b/.github/workflows/dependency-analysis.yml
--- a/.github/workflows/dependency-analysis.yml
+++ b/.github/workflows/dependency-analysis.yml
@@ -16,7 +16,125 @@ jobs:
 
       - name: Run dependency scan
         run: |
+          ERROR_LOG="error_log.txt"
+          DEP_LIST="blacklist/compromised-packages.txt"
+          LOCKFILES=($(find ./ -name "package-lock.json" -o -name "pnpm-lock.yaml" -o -name "yarn.lock"))
+          COUNT=0
+
+          function setupErrorLogFile() {
+            if [ -n "$ERROR_LOG" ]; then rm -f "$ERROR_LOG"; fi
+            if [ ! -w "$ERROR_LOG" ]; then touch "$ERROR_LOG"; fi
+          }
+
+          function checkPnpmLockfile() {
+            # Find dependency formated as
+            # "name@version:"
+            if grep -qF "$NAME@$VERSION" "$LOCKFILE"; then
+              echo "$NAME:$VERSION Was found in $LOCKFILE"
+              echo "::error:: $NAME:$VERSION Was found in $LOCKFILE" >> "$ERROR_LOG"
+            else
+                echo -n "."
+            fi
+          }
+
+          function checkNpmLockfile() {
+            # Find dependencies formated as
+            # "@accordproject/concerto-linter-default-ruleset": {
+            #      "version": "3.24.1",
+            local package="$1"
+            local version="$2"
+            local extractedDep
+
+            extractedDep=$(awk -v name="$package" -v version="$version" '
+              /"dependencies": *{/ { in_deps=1; next }
+              in_deps && /"[^"]+": *{/ {
+                match($0, /"([^"]+)": *{/, arr)
+                dep = arr[1]
+                getline
+                if ($0 ~ /"version":/) {
+                  match($0, /"version": *"([^"]+)"/, ver)
+                  if (dep == name && ver[1] == version) {
+                    print dep " " ver[1]
+                  }
+                }
+              }
+              ' "$LOCKFILE"
+            )
+            if [[ "$extractedDep" == "$package $version" ]]; then
+              echo "$package:$version" "Was found in $LOCKFILE"
+              echo "::error:: $package:$version Was found in $LOCKFILE" >> "$ERROR_LOG"
+            else
+                echo -n "."
+            fi
+          }
+
+          function checkYarnLockfile() {
+            # Find dependencies formated as
+            # "@aashutoshrathi/word-wrap@^1.2.3":
+            #    version "1.2.6"
+
+            local package="$1"
+            local version="$2"
+            local extractedDep
+          
+            extractedDep=$(awk -v pkg="$package" '
+                /^".*":$/ {
+                  split($0, arr, ",")
+                  dep=arr[1]
+                  gsub(/"/, "", dep)
+                  sub(/@[^@]*$/, "", dep)
+                  current_pkg=dep
+                }
+                /version "/ {
+                  match($0, /"([^"]+)"/, v)
+                  if(current_pkg==pkg) print current_pkg, v[1]
+                }
+              ' "$LOCKFILE")
+            if [[ "$extractedDep" == "$package $version" ]]; then
+              echo "$package:$version Was found in $LOCKFILE"
+              echo "::error:: $package:$version Was found in $LOCKFILE" >> "$ERROR_LOG"
+            else
+                echo -n "."
+            fi
+          }
+
+          function checkManifest() {
+            echo "::info:: Testing manifest = $LOCKFILE"
+            manifest_type=$(basename "$LOCKFILE")
+
+            while IFS=':' read -r NAME VERSION; do
+              # ignore empty and commented lines
+              [[ -z "${NAME// }" ]] && continue
+              [[ "$NAME" =~ ^# ]] && continue
+              #echo "DEBUG To check $NAME $VERSION"
+              case "$manifest_type" in
+                "pnpm-lock.yaml")
+                  checkPnpmLockfile
+                  ;;
+                "yarn.lock")
+                  checkYarnLockfile "$NAME" "$VERSION"
+                  ;;
+                "package-lock.json")
+                  checkNpmLockfile "$NAME" "$VERSION"
+                  ;;
+                "*")
+                  echo "KO manifest not managed"
+                  exit 1
+              esac
+              COUNT=$((COUNT+1))
+            done < "$DEP_LIST"
+            echo "Scanned $COUNT IOC"
+          }
+
           wget https://github.com/centreon/security-tools/blob/SECU-dd-tools/blacklist/compromised-packages.txt
-          wget https://raw.githubusercontent.com/centreon/security-tools/SECU-dd-tools/.github/scripts/dependencies_check.sh
-          ./dependencies_check.sh
+          setupErrorLogFile
+          for LOCKFILE in "${LOCKFILES[@]}"; do
+            checkManifest "$LOCKFILE"
+          done
+          if [ -n "$ERROR_LOG" ]; then
+            echo "FATAL Breaking the run as following dependencies were found:"
+            cat "$ERROR_LOG"
+            exit 1
+          fi
+
         shell: bash
