Apply suggestion from @sc979
Signed-off-by: Stéphane Chapron <34628915+sc979@users.noreply.github.com>

diff --git a/.github/workflows/gitleaks-analysis.yml b/.github/workflows/gitleaks-analysis.yml
--- a/.github/workflows/gitleaks-analysis.yml
+++ b/.github/workflows/gitleaks-analysis.yml
@@ -46,13 +46,13 @@ jobs:
 
           if [ $EXIT_CODE -eq 0 ]; then
             echo "No secrets found."
-          elif [ $EXIT_CODE -eq 2 ]; then
-            echo "::error::Gitleaks has detected secrets in this branch!"
-            exit 1
           elif [ $EXIT_CODE -eq 1 ]; then
             # Code 1 = invalid revision range, merge commit, etc.
             echo "::warning::Gitleaks encountered a git error (exit code: ${EXIT_CODE}). Likely an invalid revision range due to a merge commit. Scan skipped for this run."
             exit 0
+          elif [ $EXIT_CODE -eq 2 ]; then
+            echo "::error::Gitleaks has detected secrets in this branch!"
+            exit 1
           else
             # Code 128 =missing commit in history or unmanaged case
             echo "::error::Gitleaks encountered an internal error (exit code: ${EXIT_CODE}). Contact the security team to investigate."
